name: Fluxur Commit Notifier

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send to Fluxur
        run: |
          curl -X POST ${{ secrets.FLUXUR_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🚀 New commit pushed!\nRepo: ${{ github.repository }}\nAuthor: ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}\"
          }"
